feat: Add model training notebook (PH)
thinkingmachines/unicef-ai4d-poverty-mapping pull request #76
Opened 2023-01-13 08:59 UTC by tm-jc-nacpil

# Overview
Addresses #72 

This PR add the end-to-end initial model training notebook for the Philippines. The notebook processes the features given the PH DHS clusters, prepares the data, performs (simple) cross-validation evaluation, and finally trains and evaluates a random forest model to predict the wealth index

Input
- Input DHS cluster data for the Philippines

Output
- Cached OSM, Ookla, VIIRS datasets
- trained model (not yet saved)
- cross validation metrics (5-fold cross-validation, repeated): mean R^2 of 0.58 (0.04 std)
- final training metrics and feature importance graphs

![image](https://user-images.githubusercontent.com/105769386/212278564-ac044a1e-d9b6-4794-9b75-b671c338c98c.png)
![image](https://user-images.githubusercontent.com/105769386/212278587-20f179d3-8daf-48c6-bc47-c0bafc8d7666.png)

## Notes
- The initial downloading of the datasets takes very long since it's downloading many different datasets to disk. Expect to wait around 2-4 hours while the datasets are being downloaded. 
- The final R^2 achieved is much lower than the cross-validated R^2, likely due to chance. Changing the train_test_seed sometimes results in R^2 = 0.58 and higher instead
- I borrowed some of the evaluation functions. We can collect these into a model_utils module in the future. 
- Spatial cross-validation is yet to be implemented

2023-01-13 09:24 UTC, butchtm requested changes
Just remove the update to requirements.in (fastprogress is listed twice)
and resubmit for review

2023-01-13 09:24 UTC, butchtm commented on requirements.in
> -fastparquet
I think the fastprogress package is listed twice and can be removed?

2023-01-13 10:03 UTC, alronlam commented
<p>In summary, I think what's important is we use SHAP for feature importance. Random forest feature importance can be quite unstable. Good to do it soon so that's what we report in our sprint review. </p><p> </p><p>Have some reference code for generating simplified SHAP charts from our air quality repo: hhttps://github.com/thinkingmachines/unicef-ai4d-air-quality/blob/main/scripts/train.py#L98-L117</p><p>https://github.com/thinkingmachines/unicef-ai4d-air-quality/blob/main/src/modelling/eval_utils.py#L81</p><p> </p><p>The others we can improve later on :D </p>

2023-01-16 09:28 UTC, butchtm approved these changes

2023-01-16 09:28 UTC, merged